<?php
/**
 * Mastodon Feed Plugin - Configuration Example
 *
 * This file demonstrates how to override default plugin settings using PHP constants.
 * These constants can be defined in your wp-config.php file to set site-wide defaults
 * that will be applied before the admin settings page values.
 *
 * IMPORTANT: Do NOT edit this file directly!
 *
 * To use these constants:
 * 1. Open your wp-config.php file
 * 2. Find the line: /* Add any custom values between this line and the "stop editing" line. *\/
 * 3. Copy the constant definitions you want to customize from below
 * 4. Paste them between that line and /* That's all, stop editing! Happy publishing. *\/
 * 5. Modify the values as needed
 *
 * Example in wp-config.php:
 *
 *   // Custom Mastodon Feed defaults
 *   define('MASTODON_FEED_DEFAULT_INSTANCE', 'fosstodon.org');
 *   define('MASTODON_FEED_LIMIT', 20);
 *   define('MASTODON_FEED_STYLE_ACCENT_COLOR', '#FF6B6B');
 *
 * Note: Constants defined in wp-config.php take precedence over the plugin's defaults,
 * but users can still override them via the admin settings page (Settings > Mastodon Feed).
 *
 * @package MastodonFeed
 */

// ==============================================================================
// GENERAL SETTINGS
// ==============================================================================

/**
 * Default Mastodon instance hostname (without https://).
 * Default: 'mastodon.social'
 */
// define('MASTODON_FEED_DEFAULT_INSTANCE', 'mastodon.social');

/**
 * Default number of posts to display.
 * Default: 10
 */
// define('MASTODON_FEED_LIMIT', 10);

/**
 * HTTP request timeout in seconds.
 * How long to wait for Mastodon API responses before timing out
 * Default: 5
 */
// define('MASTODON_FEED_HTTP_TIMEOUT', 5);

// ==============================================================================
// FEED FILTERS
// ==============================================================================

/**
 * Exclude boosted/reblogged posts from feed.
 * Default: false
 */
// define('MASTODON_FEED_EXCLUDE_BOOSTS', false);

/**
 * Exclude reply posts from feed.
 * Default: false
 */
// define('MASTODON_FEED_EXCLUDE_REPLIES', false);

/**
 * Only show pinned posts.
 * Default: false
 */
// define('MASTODON_FEED_ONLY_PINNED', false);

/**
 * Only show posts containing media attachments.
 * Default: false
 */
// define('MASTODON_FEED_ONLY_MEDIA', false);

/**
 * Filter posts to only show those with a specific tag (without # symbol).
 * Default: false (empty string)
 */
// define('MASTODON_FEED_TAGGED', '');

// ==============================================================================
// DISPLAY OPTIONS
// ==============================================================================

/**
 * Link target for all links in posts.
 * Options: '_blank', '_self', '_parent', '_top'
 * Default: '_blank'
 */
// define('MASTODON_FEED_LINKTARGET', '_blank');

/**
 * Show preview cards from posts.
 * Default: true
 */
// define('MASTODON_FEED_SHOW_PREVIEWCARDS', true);

/**
 * Show post author information.
 * Default: true
 */
// define('MASTODON_FEED_SHOW_POST_AUTHOR', true);

/**
 * Show date and time in status meta information.
 * Default: true
 */
// define('MASTODON_FEED_SHOW_DATETIME', true);

/**
 * PHP date/time format string.
 * See: https://www.php.net/manual/en/datetime.format.php
 * Default: 'Y-m-d h:i a'
 */
// define('MASTODON_FEED_DATETIME_FORMAT', 'Y-m-d h:i a');

// ==============================================================================
// STYLING
// ==============================================================================

/**
 * Post background color (supports rgba for transparency).
 * Default: 'rgba(219,219,219,0.8)'
 */
// define('MASTODON_FEED_STYLE_BG_COLOR', 'rgba(219,219,219,0.8)');

/**
 * Post font/text color.
 * Default: '#000000'
 */
// define('MASTODON_FEED_STYLE_FONT_COLOR', '#000000');

/**
 * Accent color for links and highlights.
 * Default: '#6364FF'
 */
// define('MASTODON_FEED_STYLE_ACCENT_COLOR', '#6364FF');

/**
 * Accent font color (used when accent color is the background).
 * Default: '#ffffff'
 */
// define('MASTODON_FEED_STYLE_ACCENT_FONT_COLOR', '#ffffff');

/**
 * Border radius for containers (CSS length value).
 * Examples: '0.25rem', '10px', '0'
 * Default: '0.25rem'
 */
// define('MASTODON_FEED_STYLE_BORDER_RADIUS', '0.25rem');

// ==============================================================================
// TEXT CUSTOMIZATION
// ==============================================================================

/**
 * Text displayed when no posts are available.
 * Default: 'No posts available'
 */
// define('MASTODON_FEED_TEXT_NO_POSTS', 'No posts available');

/**
 * Boosted post indicator text.
 * Default: 'boosted 🚀'
 */
// define('MASTODON_FEED_TEXT_BOOSTED', 'boosted 🚀');

/**
 * Text for content warning buttons.
 * Default: 'Show content'
 */
// define('MASTODON_FEED_TEXT_SHOW_CONTENT', 'Show content');

/**
 * Text before post permalink (date & time).
 * Default: 'on'
 */
// define('MASTODON_FEED_TEXT_PREDATETIME', 'on');

/**
 * Text after post permalink (date & time).
 * Default: '' (empty string)
 */
// define('MASTODON_FEED_TEXT_POSTDATETIME', '');

/**
 * Text indicating edited posts.
 * Default: '(edited)'
 */
// define('MASTODON_FEED_TEXT_EDITED', '(edited)');
